language: csharp
mono: none
dotnet: 2.1.300
env:
  # Docker slug
  - DOCKER_REPO_SLUG=fewbox/sample-istio-photo
install:
 - dotnet restore
script:
 - dotnet publish Sample-Istio-Photo.csproj
 - cd $TRAVIS_BUILD_DIR/bin/Debug/netcoreapp2.1/publish
 - cp $TRAVIS_BUILD_DIR/Dockerfile ./
 - docker build -t $DOCKER_REPO_SLUG:$TRAVIS_JOB_NUMBER .
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 - docker push $DOCKER_REPO_SLUG:$TRAVIS_JOB_NUMBER