# Service #
apiVersion: v1
kind: Service
metadata:
  name: sample-istio-photo
  labels:
    app: sample-istio-photo
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: sample-istio-photo
---
# Deployment #
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-istio-photo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-istio-photo
    spec:
      containers:
      - name: sample-istio-photo
        image: fewbox/sample-istio-photo:latest
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Docker"
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        volumeMounts:
        - name: settings
          mountPath: /app/settings
          readOnly: true
      volumes:
      - name: settings
        secret:
          secretName: sample-istio-photo-secrets
# kubectl create secret generic sample-istio-photo-secrets --from-file=./appsettings.json #
---
# ServiceEntry #
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: unsplash-external
spec:
  hosts:
  - api.unsplash.com
  addresses:
  - 0.0.0.0/0
  ports:
  - name: https
    number: 443
    protocol: https
  location: MESH_EXTERNAL