# Service #
apiVersion: v1
kind: Service
metadata:
  name: sample-istio-photo
  labels:
    app: sample-istio-photo
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: sample-istio-photo
---
# Deployment #
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-istio-photo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-istio-photo
    spec:
      containers:
      - name: sample-istio-photo
        image: fewbox/sample-istio-photo:v1
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        volumeMounts:
        - name: settings
          mountPath: /app/settings
          readOnly: true
      volumes:
      - name: settings
        secret:
          secretName: sample-istio-photo-secrets